import type { FeelingId } from "@/lib/content";

/*
 * Destination catalogue — from docs/BLUEPRINT.md (sections 4 and 5) plus the
 * international extension. Kashi trips link to full journey pages; every other
 * trip is planned on request until its region opens.
 */

export type Format = "Solo Series" | "Private" | "Circuit" | "Festival";

export type Trip = {
  slug: string;
  name: string;
  format: Format;
  duration: string;
  summary: string;
  highlights: string[];
  feelings: FeelingId[];
  /** Full journey page, when one exists. */
  href?: string;
  /** Our own photograph for this trip, when we have one. */
  image?: string;
  price?: string;
};

export type DestinationExperience = {
  name: string;
  line: string;
  feeling: FeelingId;
};

export type Script =
  | "deva"
  | "kannada"
  | "tamil"
  | "oriya"
  | "sinhala"
  | "tibetan"
  | "khmer"
  | "javanese"
  // Scripts below use the reader's system fonts (every destination using them has a photo).
  | "gurmukhi"
  | "bengali"
  | "malayalam"
  | "gujarati"
  | "arabic"
  | "japanese"
  | "greek"
  | "thai"
  | "latin";

export type Destination = {
  slug: string;
  name: string;
  country: string;
  group: "india" | "beyond";
  status: "Now" | "Opening 2027" | "Coming later" | "On request";
  hub: string;
  places: string[];
  /** The place name in its own script, shown large on the plate. */
  native: string;
  script: Script;
  coords: string;
  line: string;
  season: string;
  /** Photography we own; destinations without it get a designed plate. */
  image?: string;
  /** Plate tone index (see DestinationPlate). */
  tone: number;
  trips: Trip[];
  experiences: DestinationExperience[];
};

export const destinations: Destination[] = [
  /* ---------------- India · Wave 1 ---------------- */
  {
    slug: "kashi",
    name: "Kashi",
    country: "India",
    group: "india",
    status: "Now",
    hub: "Varanasi",
    places: ["Sarnath", "Ramnagar", "Chunar", "Prayagraj", "Ayodhya"],
    native: "काशी",
    script: "deva",
    coords: "25.32° N · 82.97° E",
    line: "The world's oldest living city, where life and death meet on the Ganga.",
    season: "Oct – Mar · Dev Deepawali in Nov",
    image: "/images/hero-ghats.jpg",
    tone: 0,
    trips: [
      {
        slug: "banaras-unfiltered",
        name: "Banaras Unfiltered",
        format: "Solo Series",
        duration: "2N · 3D",
        price: "INR 8,999",
        summary: "A small-group weekend for independent travellers, departing every Friday.",
        highlights: ["Front-row Ganga Aarti", "Pre-dawn temple circuit", "Silk walk and two food walks"],
        feelings: ["curiosity", "awe"],
        href: "/journeys/banaras-unfiltered",
        image: "/images/holi.jpg",
      },
      {
        slug: "kashi-premium",
        name: "Wandermate Premium",
        format: "Private",
        duration: "2N · 3D",
        summary: "Our most popular journey: a boutique heritage stay, a private boat and reserved seats beside the Aarti.",
        highlights: ["VIP darshan at Kashi Vishwanath", "Private wooden boat", "Three food walks with a Kashi companion"],
        feelings: ["devotion", "awe"],
        href: "/journeys/kashi-premium",
        image: "/images/golden-boats.jpg",
      },
      {
        slug: "kashi-luxury",
        name: "Kashi in Private",
        format: "Private",
        duration: "3 – 5N",
        summary: "A serene spiritual journey with complete privacy and a rooftop Satvik feast.",
        highlights: ["Private rituals", "Rooftop dinner above the Aarti", "Personal photographer"],
        feelings: ["stillness", "indulgence"],
        href: "/journeys/kashi-luxury",
        image: "/images/sunrise-boats.jpg",
      },
      {
        slug: "spiritual-triangle",
        name: "The Spiritual Triangle",
        format: "Circuit",
        duration: "4 – 6N",
        summary: "Kashi, Ayodhya and Prayagraj joined in one seamless pilgrimage.",
        highlights: ["Kashi Vishwanath", "Ayodhya on the Saryu", "Triveni Sangam"],
        feelings: ["devotion"],
        href: "/journeys/spiritual-triangle",
        image: "/images/aarti-priest.jpg",
      },
    ],
    experiences: [
      { name: "Private sunrise boat", line: "Panchaganga to Harishchandra as the city wakes.", feeling: "stillness" },
      { name: "Ganga Aarti, front row", line: "Reserved seats at Dashashwamedh, then diyas on the river.", feeling: "awe" },
      { name: "The Silk Walk", line: "Madanpura's weavers, 15 to 20 generations at the loom.", feeling: "curiosity" },
    ],
  },

  /* ---------------- India · Wave 2 ---------------- */
  {
    slug: "braj",
    name: "Braj",
    country: "India",
    group: "india",
    status: "Opening 2027",
    hub: "Mathura",
    places: ["Vrindavan", "Barsana", "Govardhan", "Gokul"],
    native: "ब्रज",
    script: "deva",
    coords: "27.49° N · 77.67° E",
    line: "Krishna's land, where the temples sing and Holi lasts a week.",
    season: "Oct – Mar · Holi in Feb or Mar",
    image: "/images/destinations/braj.jpg",
    tone: 1,
    trips: [
      {
        slug: "braj-holi-unfiltered",
        name: "Braj Holi Unfiltered",
        format: "Solo Series",
        duration: "3N",
        summary: "The colour of Braj with a small group of independent travellers.",
        highlights: ["Lathmar Holi in Barsana", "Phoolon wali Holi in Vrindavan", "Braj food walk"],
        feelings: ["curiosity", "awe"],
      },
      {
        slug: "vrindavan-family-darshan",
        name: "Vrindavan Family Darshan",
        format: "Private",
        duration: "2 – 3N",
        summary: "An elder-friendly pilgrimage through the temples of Mathura and Vrindavan.",
        highlights: ["Banke Bihari", "Prem Mandir at dusk", "Govardhan parikrama by vehicle"],
        feelings: ["devotion"],
      },
      {
        slug: "janmashtami-in-braj",
        name: "Janmashtami in Braj",
        format: "Festival",
        duration: "2N",
        summary: "Krishna's birthday at midnight, in the city where it is celebrated most.",
        highlights: ["Midnight celebrations in Mathura", "Vrindavan temple decorations", "Yamuna aarti"],
        feelings: ["awe", "devotion"],
      },
    ],
    experiences: [
      { name: "Mangala aarti at dawn", line: "The first darshan of the day in Vrindavan.", feeling: "devotion" },
      { name: "Yamuna aarti", line: "Evening lamps at Vishram Ghat, Mathura.", feeling: "awe" },
      { name: "Sanjhi paper art", line: "Vrindavan's stencil-cut temple art, with an artist.", feeling: "curiosity" },
    ],
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    country: "India",
    group: "india",
    status: "Opening 2027",
    hub: "Rishikesh",
    places: ["Haridwar", "Devprayag"],
    native: "ऋषिकेश",
    script: "deva",
    coords: "30.09° N · 78.27° E",
    line: "Where the Ganga leaves the mountains, and the mind slows down.",
    season: "Mar – May · Sep – Nov",
    image: "/images/destinations/rishikesh.jpg",
    tone: 2,
    trips: [
      {
        slug: "ganga-stillness",
        name: "Ganga Stillness",
        format: "Private",
        duration: "3 – 4N",
        summary: "Yoga, meditation and evening aarti on a quieter stretch of the river.",
        highlights: ["Sunrise yoga with a teacher", "Vashishtha Gufa meditation", "Parmarth Niketan aarti"],
        feelings: ["stillness"],
      },
      {
        slug: "haridwar-rishikesh-darshan",
        name: "Haridwar & Rishikesh Darshan",
        format: "Private",
        duration: "2 – 3N",
        summary: "The great aarti at Har Ki Pauri and the temples above the river.",
        highlights: ["Har Ki Pauri aarti", "Mansa Devi by ropeway", "Neelkanth Mahadev"],
        feelings: ["devotion", "awe"],
      },
      {
        slug: "ganga-source-to-kashi",
        name: "The Ganga, Source to Kashi",
        format: "Circuit",
        duration: "7N",
        summary: "Follow the river from the Himalayan confluence to the ghats of Kashi.",
        highlights: ["Devprayag confluence", "Rishikesh and Haridwar", "Varanasi to finish"],
        feelings: ["awe", "stillness"],
      },
    ],
    experiences: [
      { name: "Riverside aarti", line: "Evening ceremony at Parmarth Niketan.", feeling: "awe" },
      { name: "Sunrise yoga", line: "A private class on the banks of the Ganga.", feeling: "stillness" },
      { name: "Devprayag confluence", line: "Where the Bhagirathi and Alaknanda become the Ganga.", feeling: "stillness" },
    ],
  },
  {
    slug: "rajputana",
    name: "Rajputana",
    country: "India",
    group: "india",
    status: "Opening 2027",
    hub: "Udaipur",
    places: ["Jodhpur", "Jaipur", "Kumbhalgarh", "Ranakpur"],
    native: "उदयपुर",
    script: "deva",
    coords: "24.58° N · 73.71° E",
    line: "Forts, palaces and the crafts that built them.",
    season: "Oct – Mar",
    image: "/images/destinations/rajputana.jpg",
    tone: 3,
    trips: [
      {
        slug: "rajputana-in-private",
        name: "Rajputana in Private",
        format: "Circuit",
        duration: "7 – 9N",
        summary: "Udaipur, Jodhpur and Jaipur with a private historian and heritage stays.",
        highlights: ["City Palace and Lake Pichola", "Ranakpur Jain temple", "Mehrangarh and Amber forts"],
        feelings: ["awe", "indulgence"],
      },
      {
        slug: "udaipur-lakes-and-palaces",
        name: "Udaipur: Lakes & Palaces",
        format: "Private",
        duration: "3N",
        summary: "The city of lakes at an unhurried pace, from the water and from its palaces.",
        highlights: ["Boat on Lake Pichola", "City Palace", "Folk dance at Bagore ki Haveli"],
        feelings: ["stillness", "indulgence"],
      },
      {
        slug: "jaipur-crafts-trail",
        name: "Jaipur Crafts Trail",
        format: "Private",
        duration: "2 – 3N",
        summary: "The workshops behind the Pink City's textiles and pottery.",
        highlights: ["Block printing in Bagru", "Blue pottery studio", "Amber Fort"],
        feelings: ["curiosity"],
      },
      {
        slug: "jodhpur-unfiltered",
        name: "Jodhpur Unfiltered",
        format: "Solo Series",
        duration: "3N",
        summary: "The blue city, its stepwells and the fort above it, with a small group.",
        highlights: ["Mehrangarh Fort", "Blue-city lanes", "Toorji ka Jhalra stepwell"],
        feelings: ["curiosity", "awe"],
      },
    ],
    experiences: [
      { name: "Block printing in Bagru", line: "Carve, dye and print with a family of printers.", feeling: "curiosity" },
      { name: "Evening on Lake Pichola", line: "The palaces lit up from the water.", feeling: "indulgence" },
      { name: "Stepwells of Jodhpur", line: "A walk through the city's water architecture.", feeling: "curiosity" },
    ],
  },

  /* ---------------- India · Wave 3 ---------------- */
  {
    slug: "khajuraho",
    name: "Khajuraho & Orchha",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Khajuraho",
    places: ["Orchha", "Gwalior"],
    native: "खजुराहो",
    script: "deva",
    coords: "24.85° N · 79.93° E",
    line: "A thousand years of stories carved in sandstone.",
    season: "Oct – Mar · Dance festival in Feb",
    image: "/images/destinations/khajuraho.jpg",
    tone: 4,
    trips: [
      {
        slug: "stone-and-sculpture",
        name: "Stone & Sculpture",
        format: "Circuit",
        duration: "3 – 4N",
        summary: "The temple art of Bundelkhand with an art historian.",
        highlights: ["Khajuraho Western Group", "Orchha's cenotaphs", "Gwalior Fort"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "khajuraho-dance-festival",
        name: "Khajuraho Dance Festival",
        format: "Festival",
        duration: "3N",
        summary: "India's classical dance forms performed against the temples.",
        highlights: ["Evening performances", "Temple walks by day", "Orchha add-on"],
        feelings: ["awe", "indulgence"],
      },
      {
        slug: "orchha-river-town",
        name: "Orchha, River Town",
        format: "Private",
        duration: "2N",
        summary: "A quiet medieval capital on the Betwa.",
        highlights: ["Chhatris at sunset", "Ram Raja temple aarti", "Jahangir Mahal"],
        feelings: ["stillness"],
      },
    ],
    experiences: [
      { name: "Sculpture walk", line: "Read the temple walls with an art historian.", feeling: "curiosity" },
      { name: "Betwa at sunset", line: "The royal cenotaphs from the riverbank.", feeling: "stillness" },
    ],
  },
  {
    slug: "hampi",
    name: "Hampi",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Hampi",
    places: ["Badami", "Aihole", "Pattadakal"],
    native: "ಹಂಪಿ",
    script: "kannada",
    coords: "15.33° N · 76.46° E",
    line: "The ruined capital of Vijayanagara, scattered among the boulders.",
    season: "Nov – Feb",
    image: "/images/destinations/hampi.jpg",
    tone: 5,
    trips: [
      {
        slug: "hampi-unfiltered",
        name: "Hampi Unfiltered",
        format: "Solo Series",
        duration: "3N",
        summary: "Ruins, river and boulders with a small group of independent travellers.",
        highlights: ["Virupaksha temple", "Vittala's stone chariot", "Sunrise on Matanga Hill"],
        feelings: ["curiosity", "awe"],
      },
      {
        slug: "cradle-of-temple-architecture",
        name: "Cradle of Temple Architecture",
        format: "Circuit",
        duration: "5N",
        summary: "Hampi with the early Chalukya temples of Badami, Aihole and Pattadakal.",
        highlights: ["Badami cave temples", "Aihole", "Pattadakal"],
        feelings: ["curiosity"],
      },
      {
        slug: "hampi-in-private",
        name: "Hampi in Private",
        format: "Private",
        duration: "3N",
        summary: "The ruins at their quietest hours, with a private guide.",
        highlights: ["Early access walks", "Royal Enclosure", "Riverside lunch"],
        feelings: ["stillness", "indulgence"],
      },
    ],
    experiences: [
      { name: "Coracle on the Tungabhadra", line: "A round reed boat between the boulders.", feeling: "stillness" },
      { name: "Sunrise on Matanga Hill", line: "The whole ruined city in first light.", feeling: "awe" },
    ],
  },
  {
    slug: "temple-country",
    name: "Temple Country",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Madurai",
    places: ["Thanjavur", "Kumbakonam", "Rameswaram", "Swamimalai"],
    native: "மதுரை",
    script: "tamil",
    coords: "9.93° N · 78.12° E",
    line: "Living temples where the rituals have run for a thousand years.",
    season: "Nov – Feb",
    image: "/images/destinations/temple-country.jpg",
    tone: 6,
    trips: [
      {
        slug: "temple-country",
        name: "Temple Country",
        format: "Circuit",
        duration: "5 – 6N",
        summary: "Madurai, Thanjavur, Kumbakonam and Rameswaram in one journey.",
        highlights: ["Meenakshi Amman temple", "Brihadeeswarar, Thanjavur", "Rameswaram's corridors"],
        feelings: ["devotion", "awe"],
      },
      {
        slug: "madurai-and-rameswaram",
        name: "Madurai & Rameswaram",
        format: "Private",
        duration: "3N",
        summary: "A family pilgrimage to two of the south's great temples.",
        highlights: ["Meenakshi Amman", "Ramanathaswamy temple", "Dhanushkodi"],
        feelings: ["devotion"],
      },
      {
        slug: "chola-heritage-trail",
        name: "Chola Heritage Trail",
        format: "Private",
        duration: "4N",
        summary: "The Great Living Chola Temples and the bronze-casters of Swamimalai.",
        highlights: ["Gangaikonda Cholapuram", "Darasuram", "Swamimalai bronze workshops"],
        feelings: ["curiosity", "awe"],
      },
    ],
    experiences: [
      { name: "Palliyarai night ceremony", line: "Meenakshi temple's closing ritual of the day.", feeling: "devotion" },
      { name: "Bronze casting", line: "Lost-wax casting with a Swamimalai family.", feeling: "curiosity" },
      { name: "Bharatanatyam evening", line: "A private recital in Thanjavur.", feeling: "indulgence" },
    ],
  },
  {
    slug: "odisha",
    name: "Odisha",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Puri",
    places: ["Konark", "Bhubaneswar", "Raghurajpur", "Pipli"],
    native: "ପୁରୀ",
    script: "oriya",
    coords: "19.81° N · 85.83° E",
    line: "Jagannath, the Sun Temple and a village of painters.",
    season: "Oct – Mar · Rath Yatra in Jun or Jul",
    image: "/images/destinations/odisha.jpg",
    tone: 7,
    trips: [
      {
        slug: "jagannath-darshan",
        name: "Jagannath Darshan",
        format: "Private",
        duration: "2 – 3N",
        summary: "Puri and Konark for families. Jagannath temple entry is for Hindu travellers.",
        highlights: ["Jagannath temple", "Konark Sun Temple", "Puri beach at dawn"],
        feelings: ["devotion"],
      },
      {
        slug: "rath-yatra",
        name: "Rath Yatra",
        format: "Festival",
        duration: "3N",
        summary: "The chariot festival of Jagannath, with a place to watch it well.",
        highlights: ["The chariot procession", "Festival-day planning", "Konark add-on"],
        feelings: ["awe", "devotion"],
      },
      {
        slug: "odisha-temples-and-crafts",
        name: "Temples & Crafts of Odisha",
        format: "Private",
        duration: "4N",
        summary: "Bhubaneswar's temples, Konark and the craft villages around them.",
        highlights: ["Mukteswar temple", "Raghurajpur painters", "Pipli applique"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "Pattachitra in Raghurajpur", line: "Paint with a family of chitrakars.", feeling: "curiosity" },
      { name: "Konark at sunrise", line: "The Sun Temple when the sun reaches it.", feeling: "awe" },
    ],
  },

  /* ---------------- India · More heritage ---------------- */
  {
    slug: "agra",
    name: "Agra & Fatehpur Sikri",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Agra",
    places: ["Fatehpur Sikri", "Mehtab Bagh", "Sikandra"],
    native: "आगरा",
    script: "deva",
    coords: "27.18° N · 78.01° E",
    line: "The Taj at first light, and the red city Akbar built and left.",
    season: "Oct – Mar",
    image: "/images/destinations/agra.jpg",
    tone: 13,
    trips: [
      {
        slug: "taj-at-first-light",
        name: "The Taj at First Light",
        format: "Private",
        duration: "2N",
        summary: "Sunrise at the Taj, and sunset from Mehtab Bagh across the Yamuna.",
        highlights: ["Taj Mahal at sunrise", "Agra Fort", "Mehtab Bagh at sunset"],
        feelings: ["awe"],
      },
      {
        slug: "mughal-heartland",
        name: "The Mughal Heartland",
        format: "Circuit",
        duration: "4N",
        summary: "Delhi, Agra and Fatehpur Sikri — three capitals of one empire.",
        highlights: ["Humayun's Tomb", "Taj Mahal", "Fatehpur Sikri"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "marble-and-memory",
        name: "Marble & Memory",
        format: "Private",
        duration: "3N",
        summary: "The Taj, and the families who still inlay marble the Mughal way.",
        highlights: ["A pietra dura workshop", "Itimad-ud-Daulah", "Akbar's tomb at Sikandra"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "Pietra dura with a craftsman", line: "Inlay a small marble tile with a family of inlayers.", feeling: "curiosity" },
      { name: "Mehtab Bagh at dusk", line: "The Taj across the river as the light goes.", feeling: "stillness" },
    ],
  },
  {
    slug: "delhi",
    name: "Delhi",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "New Delhi",
    places: ["Old Delhi", "Mehrauli", "Nizamuddin"],
    native: "दिल्ली",
    script: "deva",
    coords: "28.61° N · 77.21° E",
    line: "Seven cities on one plain, from the Qutub to Chandni Chowk.",
    season: "Oct – Mar",
    image: "/images/destinations/delhi.jpg",
    tone: 14,
    trips: [
      {
        slug: "seven-cities-of-delhi",
        name: "Seven Cities of Delhi",
        format: "Private",
        duration: "3N",
        summary: "From the Qutub Minar to Shahjahanabad: the capitals buried under the capital.",
        highlights: ["Qutub Minar", "Humayun's Tomb", "Red Fort and Jama Masjid"],
        feelings: ["curiosity", "awe"],
      },
      {
        slug: "old-delhi-after-dark",
        name: "Old Delhi After Dark",
        format: "Solo Series",
        duration: "2N",
        summary: "Small-group evenings in the lanes of Shahjahanabad.",
        highlights: ["Chandni Chowk food walk", "Jama Masjid at sunset", "Qawwali at Nizamuddin"],
        feelings: ["curiosity", "indulgence"],
      },
      {
        slug: "sufi-delhi",
        name: "Sufi Delhi",
        format: "Private",
        duration: "2N",
        summary: "The dargahs, music and poetry of the city's Sufi saints.",
        highlights: ["Nizamuddin Dargah", "Mehrauli Archaeological Park", "Ghalib's haveli"],
        feelings: ["devotion", "stillness"],
      },
    ],
    experiences: [
      { name: "Qawwali at Nizamuddin", line: "Sufi music in the courtyard of the dargah.", feeling: "devotion" },
      { name: "Chandni Chowk at dawn", line: "The spice market and parathas before the crowds.", feeling: "curiosity" },
      { name: "Lodhi Garden walk", line: "Fifteenth-century tombs in a city park.", feeling: "stillness" },
    ],
  },
  {
    slug: "amritsar",
    name: "Amritsar",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Amritsar",
    places: ["Golden Temple", "Jallianwala Bagh", "Attari–Wagah"],
    native: "ਅੰਮ੍ਰਿਤਸਰ",
    script: "gurmukhi",
    coords: "31.63° N · 74.87° E",
    line: "The Golden Temple, the kitchen that feeds thousands, and the border at dusk.",
    season: "Oct – Mar",
    image: "/images/destinations/amritsar.jpg",
    tone: 15,
    trips: [
      {
        slug: "golden-temple-at-dawn",
        name: "Golden Temple at Dawn",
        format: "Private",
        duration: "2N",
        summary: "The Palki Sahib procession, seva in the langar and the temple lit at night.",
        highlights: ["Palki Sahib ceremony", "Seva in the langar", "The Golden Temple by night"],
        feelings: ["devotion", "awe"],
      },
      {
        slug: "punjab-heritage-trail",
        name: "Punjab Heritage Trail",
        format: "Circuit",
        duration: "4N",
        summary: "Amritsar's lanes, the Wagah ceremony and a farm stay in rural Punjab.",
        highlights: ["Jallianwala Bagh", "Attari–Wagah ceremony", "A village farm stay"],
        feelings: ["curiosity"],
      },
      {
        slug: "amritsari-by-the-plate",
        name: "Amritsari by the Plate",
        format: "Solo Series",
        duration: "2N",
        summary: "Kulchas, lassi and dhabas with a small group of travellers.",
        highlights: ["Amritsari kulcha", "Old-city food walk", "Langar at the Golden Temple"],
        feelings: ["indulgence"],
      },
    ],
    experiences: [
      { name: "Seva in the langar", line: "Roll rotis beside volunteers in one of the world's largest free kitchens.", feeling: "devotion" },
      { name: "Kulcha breakfast", line: "Butter-laden Amritsari kulcha in the old city.", feeling: "indulgence" },
    ],
  },
  {
    slug: "ladakh",
    name: "Ladakh",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Leh",
    places: ["Thiksey", "Hemis", "Nubra Valley"],
    native: "ལ་དྭགས",
    script: "tibetan",
    coords: "34.15° N · 77.58° E",
    line: "Monasteries on ridgelines, high desert and the sound of prayer flags.",
    season: "Jun – Sep",
    image: "/images/destinations/ladakh.jpg",
    tone: 16,
    trips: [
      {
        slug: "monasteries-of-the-indus",
        name: "Monasteries of the Indus",
        format: "Private",
        duration: "5N",
        summary: "Morning prayers at Thiksey, Hemis and Alchi, with time to acclimatise.",
        highlights: ["Thiksey morning puja", "Hemis", "Alchi's thousand-year-old murals"],
        feelings: ["stillness", "awe"],
      },
      {
        slug: "hemis-festival",
        name: "Hemis Festival",
        format: "Festival",
        duration: "5N",
        summary: "Masked cham dances in the courtyard at Hemis, in early summer.",
        highlights: ["Cham dances", "Leh Palace", "Shey"],
        feelings: ["awe"],
      },
      {
        slug: "nubra-and-the-high-passes",
        name: "Nubra & the High Passes",
        format: "Circuit",
        duration: "7N",
        summary: "Over the mountain passes to the dunes and monasteries of Nubra.",
        highlights: ["Diskit Monastery", "Hunder dunes", "Pangong Tso"],
        feelings: ["awe", "stillness"],
      },
    ],
    experiences: [
      { name: "Morning puja at Thiksey", line: "Horns and chanting at first light.", feeling: "devotion" },
      { name: "A Ladakhi kitchen", line: "Skyu and butter tea in a village home.", feeling: "indulgence" },
    ],
  },
  {
    slug: "kolkata",
    name: "Kolkata & Bengal",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Kolkata",
    places: ["Kumartuli", "Shantiniketan", "Bishnupur"],
    native: "কলকাতা",
    script: "bengali",
    coords: "22.57° N · 88.36° E",
    line: "The city of Tagore and Durga Puja, terracotta temples and old Calcutta.",
    season: "Oct – Feb · Durga Puja in Oct",
    image: "/images/destinations/kolkata.jpg",
    tone: 17,
    trips: [
      {
        slug: "durga-puja-in-kolkata",
        name: "Durga Puja in Kolkata",
        format: "Festival",
        duration: "4N",
        summary: "Pandal nights, dhunuchi dances and the goddess's farewell on the river.",
        highlights: ["Kumartuli idol-makers", "Pandal-hopping", "Sindoor Khela"],
        feelings: ["awe", "devotion"],
      },
      {
        slug: "old-calcutta",
        name: "Old Calcutta",
        format: "Private",
        duration: "3N",
        summary: "Colonial avenues, North Kolkata's rajbaris and a ferry on the Hooghly.",
        highlights: ["Victoria Memorial", "North Kolkata rajbaris", "Hooghly ferry"],
        feelings: ["curiosity"],
      },
      {
        slug: "tagore-and-terracotta",
        name: "Tagore & Terracotta",
        format: "Circuit",
        duration: "5N",
        summary: "Tagore's Shantiniketan and the terracotta temples of Bishnupur.",
        highlights: ["Shantiniketan", "Bishnupur's temples", "A Baul music evening"],
        feelings: ["curiosity", "stillness"],
      },
    ],
    experiences: [
      { name: "Kumartuli workshops", line: "Clay idols shaped by hand before the Puja.", feeling: "curiosity" },
      { name: "A Baul evening", line: "Wandering minstrels sing in the countryside.", feeling: "stillness" },
      { name: "The sweet shops of Kolkata", line: "Rosogolla and sandesh from century-old counters.", feeling: "indulgence" },
    ],
  },
  {
    slug: "kerala",
    name: "Kerala",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Kochi",
    places: ["Fort Kochi", "Thrissur", "Alleppey"],
    native: "കേരളം",
    script: "malayalam",
    coords: "9.93° N · 76.26° E",
    line: "Spice ports, temple elephants, Kathakali and slow backwaters.",
    season: "Sep – Mar",
    image: "/images/destinations/kerala.jpg",
    tone: 18,
    trips: [
      {
        slug: "the-spice-coast",
        name: "The Spice Coast",
        format: "Private",
        duration: "3N",
        summary: "Fort Kochi's Chinese nets, Jew Town and the spice warehouses of Mattancherry.",
        highlights: ["Chinese fishing nets", "Paradesi Synagogue", "Mattancherry Palace murals"],
        feelings: ["curiosity"],
      },
      {
        slug: "thrissur-pooram",
        name: "Thrissur Pooram",
        format: "Festival",
        duration: "3N",
        summary: "Caparisoned elephants and percussion orchestras at Kerala's grandest temple festival.",
        highlights: ["Kudamattam", "Elanjithara Melam", "Fireworks"],
        feelings: ["awe"],
      },
      {
        slug: "arts-and-backwaters",
        name: "Arts & Backwaters",
        format: "Circuit",
        duration: "6N",
        summary: "Kathakali, Kalaripayattu and a slow boat through the backwaters.",
        highlights: ["Kathakali make-up and performance", "Kalaripayattu", "A night on a kettuvallam"],
        feelings: ["stillness", "curiosity"],
      },
    ],
    experiences: [
      { name: "The Kathakali green room", line: "Watch the hours of make-up before the dance.", feeling: "curiosity" },
      { name: "Sadya on a banana leaf", line: "A Kerala feast of many small dishes.", feeling: "indulgence" },
      { name: "Backwater canoe at dawn", line: "Narrow canals before the houseboats wake.", feeling: "stillness" },
    ],
  },
  {
    slug: "gujarat",
    name: "Gujarat",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Ahmedabad",
    places: ["Patan", "Modhera", "Kutch"],
    native: "ગુજરાત",
    script: "gujarati",
    coords: "23.03° N · 72.58° E",
    line: "Stepwells, a sun temple, the walled city of Ahmedabad and the white Rann.",
    season: "Nov – Feb",
    image: "/images/destinations/gujarat.jpg",
    tone: 19,
    trips: [
      {
        slug: "stepwells-and-sun-temples",
        name: "Stepwells & Sun Temples",
        format: "Circuit",
        duration: "4N",
        summary: "Rani ki Vav, Adalaj and the Sun Temple at Modhera.",
        highlights: ["Rani ki Vav", "Modhera Sun Temple", "Adalaj stepwell"],
        feelings: ["awe"],
      },
      {
        slug: "the-pols-of-ahmedabad",
        name: "The Pols of Ahmedabad",
        format: "Private",
        duration: "2N",
        summary: "India's first World Heritage City, lane by lane.",
        highlights: ["Heritage walk at dawn", "Sidi Saiyyed jali", "Sabarmati Ashram"],
        feelings: ["curiosity"],
      },
      {
        slug: "kutch-and-the-white-rann",
        name: "Kutch & the White Rann",
        format: "Circuit",
        duration: "5N",
        summary: "The craft villages of Kutch and full-moon nights on the salt desert.",
        highlights: ["Rann Utsav", "Bhujodi weavers", "Ajrakh block printers"],
        feelings: ["awe", "curiosity"],
      },
    ],
    experiences: [
      { name: "Ajrakh printing", line: "Block-print cloth with a family of Ajrakh makers.", feeling: "curiosity" },
      { name: "A Gujarati thali", line: "An unlimited thali in an old Ahmedabad house.", feeling: "indulgence" },
    ],
  },
  {
    slug: "goa",
    name: "Old Goa",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Panaji",
    places: ["Old Goa", "Fontainhas", "Ponda"],
    native: "गोंय",
    script: "deva",
    coords: "15.50° N · 73.91° E",
    line: "Baroque churches, painted Latin-quarter lanes, and Goa beyond the beaches.",
    season: "Nov – Feb",
    image: "/images/destinations/goa.jpg",
    tone: 20,
    trips: [
      {
        slug: "churches-of-old-goa",
        name: "Churches of Old Goa",
        format: "Private",
        duration: "2N",
        summary: "The Basilica of Bom Jesus, the Se Cathedral and the convents of a lost capital.",
        highlights: ["Basilica of Bom Jesus", "Se Cathedral", "Church of St Cajetan"],
        feelings: ["awe", "stillness"],
      },
      {
        slug: "fontainhas-and-feni",
        name: "Fontainhas & Feni",
        format: "Solo Series",
        duration: "2N",
        summary: "Painted houses, azulejo tiles and Goan kitchens, with a small group.",
        highlights: ["Fontainhas walk", "An azulejo studio", "Goan-Portuguese dinner"],
        feelings: ["curiosity", "indulgence"],
      },
      {
        slug: "temples-and-spice-farms",
        name: "Temples & Spice Farms",
        format: "Private",
        duration: "3N",
        summary: "The temples of Ponda and a spice plantation in the hinterland.",
        highlights: ["Mangueshi Temple", "Shanta Durga Temple", "Spice farm lunch"],
        feelings: ["devotion", "curiosity"],
      },
    ],
    experiences: [
      { name: "Azulejo painting", line: "Paint a tile in the Portuguese style.", feeling: "curiosity" },
      { name: "Fish curry rice", line: "Goa's everyday meal in a family home.", feeling: "indulgence" },
    ],
  },
  {
    slug: "bodh-gaya",
    name: "Bodh Gaya & Nalanda",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Gaya",
    places: ["Rajgir", "Nalanda", "Vaishali"],
    native: "बोधगया",
    script: "deva",
    coords: "24.70° N · 84.99° E",
    line: "Where the Buddha found enlightenment, and the ancient university of Nalanda.",
    season: "Oct – Mar",
    image: "/images/destinations/bodh-gaya.jpg",
    tone: 21,
    trips: [
      {
        slug: "under-the-bodhi-tree",
        name: "Under the Bodhi Tree",
        format: "Private",
        duration: "2N",
        summary: "Meditation at the Mahabodhi Temple at dawn and at dusk.",
        highlights: ["Mahabodhi Temple", "The Bodhi Tree", "Monasteries of many nations"],
        feelings: ["stillness", "devotion"],
      },
      {
        slug: "nalanda-and-rajgir",
        name: "Nalanda & Rajgir",
        format: "Circuit",
        duration: "4N",
        summary: "The ruins of Nalanda, and Vulture's Peak where the Buddha taught.",
        highlights: ["Nalanda ruins", "Vulture's Peak", "Rajgir"],
        feelings: ["curiosity", "stillness"],
      },
      {
        slug: "kashi-to-bodh-gaya",
        name: "Kashi to Bodh Gaya",
        format: "Circuit",
        duration: "5N",
        summary: "From Sarnath, where the Buddha first taught, to Bodh Gaya, where he awoke.",
        highlights: ["Sarnath", "Bodh Gaya", "Nalanda"],
        feelings: ["devotion"],
      },
    ],
    experiences: [
      { name: "Dawn under the Bodhi Tree", line: "Sit in silence as the monks arrive.", feeling: "stillness" },
      { name: "The monastery trail", line: "Thai, Tibetan and Japanese temples in one small town.", feeling: "curiosity" },
    ],
  },
  {
    slug: "ajanta-ellora",
    name: "Ajanta & Ellora",
    country: "India",
    group: "india",
    status: "Coming later",
    hub: "Chhatrapati Sambhajinagar",
    places: ["Ajanta", "Ellora", "Daulatabad"],
    native: "वेरूळ",
    script: "deva",
    coords: "20.03° N · 75.18° E",
    line: "Painted Buddhist caves, and a temple carved down from a single rock.",
    season: "Oct – Mar",
    image: "/images/destinations/ajanta-ellora.jpg",
    tone: 22,
    trips: [
      {
        slug: "caves-of-the-deccan",
        name: "Caves of the Deccan",
        format: "Private",
        duration: "3N",
        summary: "Ajanta's murals and Ellora's Kailasa, carved from the top down out of one rock.",
        highlights: ["Ajanta murals", "Kailasa temple", "Daulatabad Fort"],
        feelings: ["awe"],
      },
      {
        slug: "ellora-and-grishneshwar",
        name: "Ellora & Grishneshwar",
        format: "Private",
        duration: "2N",
        summary: "Ellora's caves with darshan at Grishneshwar, one of the twelve Jyotirlingas.",
        highlights: ["Ellora caves", "Grishneshwar Jyotirlinga", "Bibi ka Maqbara"],
        feelings: ["devotion", "awe"],
      },
      {
        slug: "domes-of-the-deccan",
        name: "Domes of the Deccan",
        format: "Circuit",
        duration: "6N",
        summary: "From Ellora to the sultanate cities of Bidar and Bijapur.",
        highlights: ["Ellora", "Bidar Fort", "Gol Gumbaz"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "Paithani weaving", line: "Watch silk Paithani saris woven on the loom.", feeling: "curiosity" },
      { name: "Kailasa in the evening", line: "The great temple as the low sun turns it gold.", feeling: "awe" },
    ],
  },

  /* ---------------- Beyond India ---------------- */
  {
    slug: "nepal",
    name: "Kathmandu & Lumbini",
    country: "Nepal",
    group: "beyond",
    status: "On request",
    hub: "Kathmandu",
    places: ["Patan", "Bhaktapur", "Lumbini"],
    native: "काठमाडौं",
    script: "deva",
    coords: "27.72° N · 85.32° E",
    line: "Pagoda temples, Newar craft and the birthplace of the Buddha.",
    season: "Oct – Apr",
    image: "/images/destinations/nepal.jpg",
    tone: 8,
    trips: [
      {
        slug: "kathmandu-valley-heritage",
        name: "Kathmandu Valley Heritage",
        format: "Private",
        duration: "4N",
        summary: "Three royal cities and the valley's great shrines.",
        highlights: ["Durbar Squares of Kathmandu, Patan and Bhaktapur", "Pashupatinath", "Boudhanath stupa"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "kashi-to-kathmandu",
        name: "Kashi to Kathmandu",
        format: "Circuit",
        duration: "6 – 7N",
        summary: "From Kashi Vishwanath to Pashupatinath, with Lumbini on the way.",
        highlights: ["Varanasi", "Lumbini", "Pashupatinath"],
        feelings: ["devotion"],
      },
      {
        slug: "footsteps-of-the-buddha",
        name: "Footsteps of the Buddha",
        format: "Circuit",
        duration: "5N",
        summary: "Where the Buddha taught, passed away and was born.",
        highlights: ["Sarnath", "Kushinagar", "Lumbini"],
        feelings: ["stillness", "devotion"],
      },
    ],
    experiences: [
      { name: "Aarti on the Bagmati", line: "The evening ceremony at Pashupatinath.", feeling: "awe" },
      { name: "Newari feast in Patan", line: "A traditional meal in a courtyard home.", feeling: "indulgence" },
      { name: "Bhaktapur's potters", line: "Throw a pot in Pottery Square.", feeling: "curiosity" },
    ],
  },
  {
    slug: "sri-lanka",
    name: "Sri Lanka",
    country: "Sri Lanka",
    group: "beyond",
    status: "On request",
    hub: "Kandy",
    places: ["Anuradhapura", "Polonnaruwa", "Sigiriya", "Nuwara Eliya"],
    native: "ලංකා",
    script: "sinhala",
    coords: "7.29° N · 80.63° E",
    line: "The Ramayana's island, and two thousand years of Buddhist kingdoms.",
    season: "Dec – Apr · Esala Perahera in Jul or Aug",
    image: "/images/destinations/sri-lanka.jpg",
    tone: 9,
    trips: [
      {
        slug: "ramayana-trail",
        name: "The Ramayana Trail",
        format: "Circuit",
        duration: "6N",
        summary: "The places Sri Lankan tradition links to the Ramayana.",
        highlights: ["Seetha Amman temple, Nuwara Eliya", "Ravana Falls", "Munneswaram temple"],
        feelings: ["devotion", "curiosity"],
      },
      {
        slug: "cultural-triangle",
        name: "The Cultural Triangle",
        format: "Circuit",
        duration: "5N",
        summary: "The ancient capitals and rock temples of the island's heart.",
        highlights: ["Anuradhapura", "Sigiriya", "Dambulla cave temples"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "esala-perahera",
        name: "Kandy Esala Perahera",
        format: "Festival",
        duration: "3N",
        summary: "The great procession of the Sacred Tooth Relic through Kandy.",
        highlights: ["Night processions", "Temple of the Tooth", "Kandy lake walk"],
        feelings: ["awe"],
      },
    ],
    experiences: [
      { name: "Evening puja in Kandy", line: "At the Temple of the Sacred Tooth Relic.", feeling: "devotion" },
      { name: "Sigiriya, early", line: "Climb the rock fortress before the heat.", feeling: "awe" },
      { name: "A morning with a tea planter", line: "From leaf to cup in the hill country.", feeling: "curiosity" },
    ],
  },
  {
    slug: "bhutan",
    name: "Bhutan",
    country: "Bhutan",
    group: "beyond",
    status: "On request",
    hub: "Paro",
    places: ["Thimphu", "Punakha"],
    native: "འབྲུག",
    script: "tibetan",
    coords: "27.43° N · 89.42° E",
    line: "Dzongs, prayer flags and festivals of masked dances.",
    season: "Mar – May · Sep – Nov",
    image: "/images/destinations/bhutan.jpg",
    tone: 10,
    trips: [
      {
        slug: "dzongs-and-valleys",
        name: "Dzongs & Valleys",
        format: "Private",
        duration: "5N",
        summary: "Paro, Thimphu and Punakha, over the Dochula pass.",
        highlights: ["Punakha Dzong", "Dochula pass", "Thimphu"],
        feelings: ["awe", "stillness"],
      },
      {
        slug: "tshechu-festival",
        name: "Tshechu Festival",
        format: "Festival",
        duration: "5N",
        summary: "Masked cham dances in a dzong courtyard, as they have been for centuries.",
        highlights: ["Festival days at the dzong", "Paro valley", "Thimphu"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "bhutan-in-stillness",
        name: "Bhutan in Stillness",
        format: "Private",
        duration: "4N",
        summary: "A slow, private journey with a farmhouse stay.",
        highlights: ["Tiger's Nest", "Farmhouse night", "Hot stone bath"],
        feelings: ["stillness", "indulgence"],
      },
    ],
    experiences: [
      { name: "Tiger's Nest", line: "The hike to Paro Taktsang on its cliff.", feeling: "awe" },
      { name: "Archery with locals", line: "Bhutan's national sport, on a village range.", feeling: "curiosity" },
      { name: "Hot stone bath", line: "A traditional bath in a farmhouse.", feeling: "stillness" },
    ],
  },
  {
    slug: "cambodia",
    name: "Angkor",
    country: "Cambodia",
    group: "beyond",
    status: "On request",
    hub: "Siem Reap",
    places: ["Angkor", "Beng Mealea", "Koh Ker", "Phnom Penh"],
    native: "អង្គរ",
    script: "khmer",
    coords: "13.36° N · 103.86° E",
    line: "The largest religious monument on earth, and Hindu epics carved in stone.",
    season: "Nov – Mar",
    image: "/images/destinations/cambodia.jpg",
    tone: 11,
    trips: [
      {
        slug: "angkor-in-depth",
        name: "Angkor in Depth",
        format: "Private",
        duration: "4N",
        summary: "The great temples with an expert, at the hours they are quietest.",
        highlights: ["Angkor Wat", "Bayon, Angkor Thom", "Ta Prohm and Banteay Srei"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "beyond-angkor",
        name: "Beyond Angkor",
        format: "Private",
        duration: "3N",
        summary: "The jungle temples further out, and the river of a thousand lingas.",
        highlights: ["Beng Mealea", "Koh Ker", "Kbal Spean"],
        feelings: ["curiosity", "stillness"],
      },
      {
        slug: "angkor-and-phnom-penh",
        name: "Angkor & Phnom Penh",
        format: "Circuit",
        duration: "6N",
        summary: "Siem Reap's temples with the capital's royal palace and museum.",
        highlights: ["Angkor Wat", "Royal Palace and Silver Pagoda", "National Museum"],
        feelings: ["awe"],
      },
    ],
    experiences: [
      { name: "Angkor Wat at sunrise", line: "The towers against first light.", feeling: "awe" },
      { name: "The Churning of the Ocean", line: "Angkor Wat's great bas-relief, with an expert.", feeling: "curiosity" },
      { name: "Apsara dance", line: "Classical Khmer dance in Siem Reap.", feeling: "indulgence" },
    ],
  },
  {
    slug: "java-bali",
    name: "Java & Bali",
    country: "Indonesia",
    group: "beyond",
    status: "On request",
    hub: "Yogyakarta",
    places: ["Borobudur", "Prambanan", "Ubud"],
    native: "ꦗꦮ",
    script: "javanese",
    coords: "7.80° S · 110.36° E",
    line: "Borobudur, Prambanan and the Ramayana danced under the stars.",
    season: "Apr – Oct",
    image: "/images/destinations/java-bali.jpg",
    tone: 12,
    trips: [
      {
        slug: "borobudur-and-prambanan",
        name: "Borobudur & Prambanan",
        format: "Private",
        duration: "4N",
        summary: "Java's great Buddhist and Hindu monuments from Yogyakarta.",
        highlights: ["Borobudur", "Prambanan", "Yogyakarta Kraton"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "bali-temples-and-terraces",
        name: "Bali: Temples & Terraces",
        format: "Private",
        duration: "5N",
        summary: "Bali's water temples and rice terraces, away from the beaches.",
        highlights: ["Tirta Empul", "Besakih", "Jatiluwih rice terraces"],
        feelings: ["stillness", "devotion"],
      },
      {
        slug: "java-to-bali",
        name: "Java to Bali",
        format: "Circuit",
        duration: "8N",
        summary: "Two islands, one thread: the Hindu-Buddhist heritage of the archipelago.",
        highlights: ["Borobudur and Prambanan", "Ubud", "Bali's water temples"],
        feelings: ["awe", "indulgence"],
      },
    ],
    experiences: [
      { name: "Ramayana Ballet", line: "Open-air performance with Prambanan behind the stage.", feeling: "awe" },
      { name: "Batik in Yogyakarta", line: "Wax-resist dyeing with a batik master.", feeling: "curiosity" },
      { name: "Tirta Empul", line: "The water purification ritual at a spring temple.", feeling: "devotion" },
    ],
  },

  /* ---------------- Beyond India · Worldwide ---------------- */
  {
    slug: "kyoto",
    name: "Kyoto & Nara",
    country: "Japan",
    group: "beyond",
    status: "On request",
    hub: "Kyoto",
    places: ["Nara", "Arashiyama", "Koyasan"],
    native: "京都",
    script: "japanese",
    coords: "35.01° N · 135.77° E",
    line: "Temples, tea, and the long road Buddhism took east from India.",
    season: "Mar – May · Oct – Nov",
    image: "/images/destinations/kyoto.jpg",
    tone: 23,
    trips: [
      {
        slug: "temples-of-kyoto",
        name: "Temples of Kyoto",
        format: "Private",
        duration: "5N",
        summary: "Zen gardens, the gates of Fushimi Inari and Nara's Great Buddha.",
        highlights: ["Fushimi Inari", "Ryoan-ji", "Todai-ji, Nara"],
        feelings: ["stillness", "awe"],
      },
      {
        slug: "a-night-on-koyasan",
        name: "A Night on Koyasan",
        format: "Private",
        duration: "4N",
        summary: "Kyoto, with a temple stay among the monks of Mount Koya.",
        highlights: ["A shukubo temple stay", "Okunoin", "Morning prayers"],
        feelings: ["devotion", "stillness"],
      },
      {
        slug: "the-craft-of-kyoto",
        name: "The Craft of Kyoto",
        format: "Private",
        duration: "4N",
        summary: "The tea ceremony, Nishijin weaving and the kitchens of Nishiki.",
        highlights: ["Tea ceremony", "Nishijin weaving", "Nishiki market"],
        feelings: ["curiosity", "indulgence"],
      },
    ],
    experiences: [
      { name: "Tea ceremony", line: "Matcha prepared in a machiya tea room.", feeling: "stillness" },
      { name: "Zazen at dawn", line: "Seated meditation with a Zen monk.", feeling: "stillness" },
    ],
  },
  {
    slug: "istanbul",
    name: "Istanbul & Cappadocia",
    country: "Türkiye",
    group: "beyond",
    status: "On request",
    hub: "Istanbul",
    places: ["Cappadocia", "Konya", "Bursa"],
    native: "İstanbul",
    script: "latin",
    coords: "41.01° N · 28.98° E",
    line: "Byzantium and the Ottomans on two continents, and Rumi's whirling dervishes.",
    season: "Apr – Jun · Sep – Nov",
    image: "/images/destinations/istanbul.jpg",
    tone: 24,
    trips: [
      {
        slug: "city-on-two-continents",
        name: "City on Two Continents",
        format: "Private",
        duration: "4N",
        summary: "Hagia Sophia, the Topkapi Palace and an evening on the Bosphorus.",
        highlights: ["Hagia Sophia", "Topkapi Palace", "The Bosphorus by boat"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "the-rumi-trail",
        name: "The Rumi Trail",
        format: "Circuit",
        duration: "6N",
        summary: "Istanbul to Konya for the sema of the whirling dervishes.",
        highlights: ["Mevlana Museum", "A sema ceremony", "Cappadocia's cave churches"],
        feelings: ["devotion", "stillness"],
      },
      {
        slug: "cappadocia-at-dawn",
        name: "Cappadocia at Dawn",
        format: "Private",
        duration: "3N",
        summary: "Balloons over the fairy chimneys, and churches painted inside the rock.",
        highlights: ["Balloon flight at sunrise", "Göreme Open-Air Museum", "An underground city"],
        feelings: ["awe"],
      },
    ],
    experiences: [
      { name: "A historic hammam", line: "A traditional Turkish bath under an Ottoman dome.", feeling: "indulgence" },
      { name: "The Grand Bazaar with a dealer", line: "Carpets and kilims, and the stories woven into them.", feeling: "curiosity" },
    ],
  },
  {
    slug: "jordan",
    name: "Petra & Wadi Rum",
    country: "Jordan",
    group: "beyond",
    status: "On request",
    hub: "Amman",
    places: ["Petra", "Wadi Rum", "Jerash"],
    native: "البتراء",
    script: "arabic",
    coords: "30.33° N · 35.44° E",
    line: "A rose-red city carved into the cliffs, and the desert of Lawrence.",
    season: "Mar – May · Sep – Nov",
    image: "/images/destinations/jordan.jpg",
    tone: 25,
    trips: [
      {
        slug: "petra-by-night",
        name: "Petra by Night",
        format: "Private",
        duration: "4N",
        summary: "The Siq at dawn, the climb to the Monastery and Petra lit by candles.",
        highlights: ["Al-Khazneh", "The Monastery", "Petra by Night"],
        feelings: ["awe"],
      },
      {
        slug: "stars-over-wadi-rum",
        name: "Stars over Wadi Rum",
        format: "Private",
        duration: "3N",
        summary: "Jeep and camel through the desert, and a night in a Bedouin camp.",
        highlights: ["Desert by jeep", "A Bedouin camp", "Stargazing"],
        feelings: ["stillness", "awe"],
      },
      {
        slug: "jerash-and-the-jordan-valley",
        name: "Jerash & the Jordan Valley",
        format: "Circuit",
        duration: "6N",
        summary: "Roman Jerash, Mount Nebo and the Dead Sea.",
        highlights: ["Jerash", "Mount Nebo", "The Dead Sea"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "A Bedouin dinner", line: "Zarb, slow-cooked under the sand.", feeling: "indulgence" },
      { name: "The Siq at first light", line: "Walk the canyon before the day's visitors.", feeling: "awe" },
    ],
  },
  {
    slug: "egypt",
    name: "Cairo & the Nile",
    country: "Egypt",
    group: "beyond",
    status: "On request",
    hub: "Cairo",
    places: ["Giza", "Luxor", "Aswan"],
    native: "مصر",
    script: "arabic",
    coords: "29.98° N · 31.13° E",
    line: "The pyramids, the temples of Luxor and the slow Nile between them.",
    season: "Oct – Apr",
    image: "/images/destinations/egypt.jpg",
    tone: 26,
    trips: [
      {
        slug: "pyramids-and-old-cairo",
        name: "Pyramids & Old Cairo",
        format: "Private",
        duration: "3N",
        summary: "Giza at opening time, the Grand Egyptian Museum and Islamic Cairo.",
        highlights: ["Pyramids of Giza", "Grand Egyptian Museum", "Khan el-Khalili"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "the-nile-by-dahabiya",
        name: "The Nile by Dahabiya",
        format: "Private",
        duration: "6N",
        summary: "Luxor to Aswan on a sailing boat, temple by temple.",
        highlights: ["Karnak and Luxor temples", "Valley of the Kings", "Edfu and Kom Ombo"],
        feelings: ["stillness", "awe"],
      },
      {
        slug: "abu-simbel-at-sunrise",
        name: "Abu Simbel at Sunrise",
        format: "Circuit",
        duration: "8N",
        summary: "Cairo, the Nile, and Ramesses II's temples above Lake Nasser.",
        highlights: ["Giza", "Luxor", "Abu Simbel"],
        feelings: ["awe"],
      },
    ],
    experiences: [
      { name: "Felucca at sunset", line: "Sail past Elephantine Island in Aswan.", feeling: "stillness" },
      { name: "Koshari in Cairo", line: "Egypt's favourite street dish.", feeling: "indulgence" },
    ],
  },
  {
    slug: "morocco",
    name: "Fes & Marrakech",
    country: "Morocco",
    group: "beyond",
    status: "On request",
    hub: "Fes",
    places: ["Fes", "Meknes", "Marrakech"],
    native: "فاس",
    script: "arabic",
    coords: "34.03° N · 5.00° W",
    line: "Medinas, madrasas and one of the world's oldest universities.",
    season: "Mar – May · Sep – Nov",
    image: "/images/destinations/morocco.jpg",
    tone: 27,
    trips: [
      {
        slug: "inside-the-medina-of-fes",
        name: "Inside the Medina of Fes",
        format: "Private",
        duration: "3N",
        summary: "Madrasas, tanneries and the riads of Fes el-Bali.",
        highlights: ["Bou Inania Madrasa", "Chouara Tannery", "Al-Qarawiyyin"],
        feelings: ["curiosity"],
      },
      {
        slug: "imperial-cities",
        name: "Imperial Cities",
        format: "Circuit",
        duration: "7N",
        summary: "Fes, Meknes, Rabat and Marrakech.",
        highlights: ["Volubilis", "Meknes", "Jemaa el-Fnaa"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "over-the-atlas-to-the-sahara",
        name: "Over the Atlas to the Sahara",
        format: "Circuit",
        duration: "6N",
        summary: "Kasbahs, the High Atlas and a night in the Merzouga dunes.",
        highlights: ["Aït Benhaddou", "Todra Gorge", "A camp in Erg Chebbi"],
        feelings: ["awe", "stillness"],
      },
    ],
    experiences: [
      { name: "A zellige workshop", line: "Cut and set tiles with a master craftsman.", feeling: "curiosity" },
      { name: "Cooking in a riad", line: "Tagine and pastilla with a Fassi family.", feeling: "indulgence" },
    ],
  },
  {
    slug: "uzbekistan",
    name: "Samarkand & Bukhara",
    country: "Uzbekistan",
    group: "beyond",
    status: "On request",
    hub: "Samarkand",
    places: ["Samarkand", "Bukhara", "Khiva"],
    native: "Samarqand",
    script: "latin",
    coords: "39.65° N · 66.96° E",
    line: "Blue domes of the Silk Road, and the homeland of the Mughals.",
    season: "Apr – Jun · Sep – Oct",
    image: "/images/destinations/uzbekistan.jpg",
    tone: 28,
    trips: [
      {
        slug: "silk-road-cities",
        name: "Silk Road Cities",
        format: "Circuit",
        duration: "7N",
        summary: "Samarkand, Bukhara and Khiva by train and road.",
        highlights: ["The Registan", "Bukhara's old city", "Itchan Kala, Khiva"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "timurs-samarkand",
        name: "Timur's Samarkand",
        format: "Private",
        duration: "3N",
        summary: "The Registan, Shah-i-Zinda and the tomb of Timur.",
        highlights: ["The Registan", "Shah-i-Zinda", "Gur-e-Amir"],
        feelings: ["awe"],
      },
      {
        slug: "roots-of-the-mughals",
        name: "Roots of the Mughals",
        format: "Circuit",
        duration: "8N",
        summary: "From Babur's Fergana Valley to Timur's Samarkand.",
        highlights: ["Fergana Valley", "Rishtan ceramics", "Samarkand"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "Suzani embroidery", line: "Silk embroidery with Bukhara's needleworkers.", feeling: "curiosity" },
      { name: "Plov in a family home", line: "Uzbekistan's rice dish, cooked in a kazan.", feeling: "indulgence" },
    ],
  },
  {
    slug: "peru",
    name: "Cusco & Machu Picchu",
    country: "Peru",
    group: "beyond",
    status: "On request",
    hub: "Cusco",
    places: ["Sacred Valley", "Machu Picchu", "Lake Titicaca"],
    native: "Qusqu",
    script: "latin",
    coords: "13.53° S · 71.97° W",
    line: "The Inca capital, the Sacred Valley and the city in the clouds.",
    season: "May – Sep",
    image: "/images/destinations/peru.jpg",
    tone: 29,
    trips: [
      {
        slug: "machu-picchu-unhurried",
        name: "Machu Picchu, Unhurried",
        format: "Private",
        duration: "5N",
        summary: "Cusco, the Sacred Valley and two visits to Machu Picchu.",
        highlights: ["Qorikancha, Cusco", "Pisac and Ollantaytambo", "Machu Picchu"],
        feelings: ["awe"],
      },
      {
        slug: "inti-raymi",
        name: "Inti Raymi",
        format: "Festival",
        duration: "5N",
        summary: "The Inca festival of the sun at Sacsayhuamán, every 24 June.",
        highlights: ["Inti Raymi", "Sacsayhuamán", "Cusco"],
        feelings: ["awe", "devotion"],
      },
      {
        slug: "weavers-of-the-andes",
        name: "Weavers of the Andes",
        format: "Private",
        duration: "4N",
        summary: "Quechua weaving villages and the markets of the Sacred Valley.",
        highlights: ["Chinchero weavers", "Moray terraces", "Maras salt pans"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "Weaving in Chinchero", line: "Natural dyes and backstrap looms.", feeling: "curiosity" },
      { name: "Pachamanca", line: "A feast cooked in an earth oven.", feeling: "indulgence" },
    ],
  },
  {
    slug: "greece",
    name: "Athens & Delphi",
    country: "Greece",
    group: "beyond",
    status: "On request",
    hub: "Athens",
    places: ["Delphi", "Meteora", "Olympia"],
    native: "Αθήνα",
    script: "greek",
    coords: "37.97° N · 23.73° E",
    line: "The Acropolis, the oracle at Delphi and monasteries on pillars of stone.",
    season: "Apr – Jun · Sep – Oct",
    image: "/images/destinations/greece.jpg",
    tone: 30,
    trips: [
      {
        slug: "classical-greece",
        name: "Classical Greece",
        format: "Circuit",
        duration: "6N",
        summary: "Athens, Delphi and Olympia.",
        highlights: ["The Acropolis", "Delphi", "Ancient Olympia"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "monasteries-of-meteora",
        name: "Monasteries of Meteora",
        format: "Private",
        duration: "3N",
        summary: "Byzantine monasteries perched on sandstone pillars.",
        highlights: ["Great Meteoron", "Varlaam", "Sunset over the rocks"],
        feelings: ["stillness", "devotion"],
      },
      {
        slug: "athens-in-depth",
        name: "Athens in Depth",
        format: "Private",
        duration: "3N",
        summary: "The Acropolis at opening, the Agora and the Plaka.",
        highlights: ["The Acropolis", "Ancient Agora", "Acropolis Museum"],
        feelings: ["curiosity"],
      },
    ],
    experiences: [
      { name: "The Acropolis at opening", line: "The Parthenon before the crowds.", feeling: "awe" },
      { name: "A taverna evening", line: "Mezze below the Acropolis.", feeling: "indulgence" },
    ],
  },
  {
    slug: "italy",
    name: "Rome & Florence",
    country: "Italy",
    group: "beyond",
    status: "On request",
    hub: "Rome",
    places: ["Rome", "Florence", "Assisi"],
    native: "Roma",
    script: "latin",
    coords: "41.90° N · 12.50° E",
    line: "Ancient Rome, the Renaissance, and the hill town of St Francis.",
    season: "Apr – Jun · Sep – Oct",
    image: "/images/destinations/italy.jpg",
    tone: 31,
    trips: [
      {
        slug: "rome-in-depth",
        name: "Rome in Depth",
        format: "Private",
        duration: "4N",
        summary: "The Colosseum, the Forum and the Vatican, without the queues.",
        highlights: ["Colosseum and Forum", "Vatican Museums", "The Pantheon"],
        feelings: ["awe"],
      },
      {
        slug: "renaissance-florence",
        name: "Renaissance Florence",
        format: "Private",
        duration: "3N",
        summary: "The Duomo, the Uffizi and the workshops of the Oltrarno.",
        highlights: ["The Duomo", "The Uffizi", "Oltrarno artisans"],
        feelings: ["curiosity"],
      },
      {
        slug: "rome-to-assisi",
        name: "Rome to Assisi",
        format: "Circuit",
        duration: "6N",
        summary: "Rome, Florence and the Umbrian hill town of St Francis.",
        highlights: ["Rome", "Florence", "Basilica of St Francis"],
        feelings: ["devotion", "stillness"],
      },
    ],
    experiences: [
      { name: "A fresco workshop", line: "Try buon fresco in a Florentine studio.", feeling: "curiosity" },
      { name: "Pasta in Trastevere", line: "A cooking class in a Roman home.", feeling: "indulgence" },
    ],
  },
  {
    slug: "thailand",
    name: "Ayutthaya & Chiang Mai",
    country: "Thailand",
    group: "beyond",
    status: "On request",
    hub: "Bangkok",
    places: ["Ayutthaya", "Sukhothai", "Chiang Mai"],
    native: "อยุธยา",
    script: "thai",
    coords: "14.35° N · 100.57° E",
    line: "Ruined royal capitals, golden temples and the Ramakien, Thailand's Ramayana.",
    season: "Nov – Feb",
    image: "/images/destinations/thailand.jpg",
    tone: 32,
    trips: [
      {
        slug: "ancient-capitals",
        name: "Ancient Capitals",
        format: "Circuit",
        duration: "6N",
        summary: "Ayutthaya and Sukhothai, and the Ramakien murals of Bangkok's Grand Palace.",
        highlights: ["Grand Palace and the Ramakien murals", "Ayutthaya", "Sukhothai"],
        feelings: ["awe", "curiosity"],
      },
      {
        slug: "temples-of-chiang-mai",
        name: "Temples of Chiang Mai",
        format: "Private",
        duration: "4N",
        summary: "Lanna temples, a monk chat and Doi Suthep at dawn.",
        highlights: ["Wat Phra That Doi Suthep", "Wat Chedi Luang", "A monk chat"],
        feelings: ["stillness", "devotion"],
      },
      {
        slug: "yi-peng-and-loy-krathong",
        name: "Yi Peng & Loy Krathong",
        format: "Festival",
        duration: "5N",
        summary: "Lanterns and floating lights over Chiang Mai in November.",
        highlights: ["Yi Peng lanterns", "Loy Krathong", "The Lanna old city"],
        feelings: ["awe"],
      },
    ],
    experiences: [
      { name: "Khon masked dance", line: "The Ramakien in classical dance-drama.", feeling: "awe" },
      { name: "The dawn alms round", line: "Monks walk the old city at first light.", feeling: "stillness" },
    ],
  },
];

export const india = destinations.filter((d) => d.group === "india");
export const beyond = destinations.filter((d) => d.group === "beyond");

export function getDestination(slug: string) {
  return destinations.find((d) => d.slug === slug);
}

export type TripWithPlace = Trip & { destination: Destination };

export const allTrips: TripWithPlace[] = destinations.flatMap((d) =>
  d.trips.map((t) => ({ ...t, destination: d })),
);

export function tripHref(t: TripWithPlace) {
  return t.href ?? `/destinations/${t.destination.slug}#${t.slug}`;
}

/** A hand-picked spread across India and beyond for the home page rail. */
export const featuredTripSlugs = [
  "angkor-in-depth",
  "temples-of-kyoto",
  "petra-by-night",
  "kashi-premium",
  "the-nile-by-dahabiya",
  "silk-road-cities",
  "golden-temple-at-dawn",
  "machu-picchu-unhurried",
  "monasteries-of-the-indus",
  "inside-the-medina-of-fes",
];

/** Festivals that recur through the year, across destinations. */
export const festivals = [
  { month: "Jan", name: "Magh Mela", place: "Prayagraj", dest: "kashi" },
  { month: "Feb", name: "Khajuraho Dance Festival", place: "Khajuraho", dest: "khajuraho" },
  { month: "Mar", name: "Holi in Braj", place: "Barsana · Vrindavan", dest: "braj" },
  { month: "Spring", name: "Paro Tshechu", place: "Bhutan", dest: "bhutan" },
  { month: "Apr – May", name: "Thrissur Pooram", place: "Thrissur", dest: "kerala" },
  { month: "Jun", name: "Inti Raymi", place: "Cusco", dest: "peru" },
  { month: "Jun – Jul", name: "Rath Yatra", place: "Puri", dest: "odisha" },
  { month: "Jun – Jul", name: "Hemis Festival", place: "Ladakh", dest: "ladakh" },
  { month: "Jul – Aug", name: "Esala Perahera", place: "Kandy", dest: "sri-lanka" },
  { month: "Aug – Sep", name: "Janmashtami", place: "Mathura · Vrindavan", dest: "braj" },
  { month: "Oct", name: "Durga Puja", place: "Kolkata", dest: "kolkata" },
  { month: "Nov", name: "Dev Deepawali", place: "Varanasi", dest: "kashi" },
  { month: "Nov", name: "Yi Peng", place: "Chiang Mai", dest: "thailand" },
];
